### ISSUE TITLE
!yt doesn't work

### ISSUE THREAD

**Issue by RealRunSpace** [SinusBot/docker#28]
Hello, I'm trying to play a youtube video and I get this in the console `err from ytdl: exit status 1`
`2019/03/08 15:34:34 cc7fbda3 7868d07b INFO   PRIVATE-CHAT [RealRunSpace]] yt [URL]https://www.youtube.com/watch?v=E8VwtjhMFJ8[/URL]
2019/03/08 15:34:34 cc7fbda3 7868d07b INFO   CHAT 1 [rrs @ RealRunSpace] < yt [URL]https://www.youtube.com/watch?v=E8VwtjhMFJ8[/URL] > / OK
2019/03/08 15:34:37 err from ytdl: exit status 1`
I have a firewall installed, but I don't know where to see logs of ytdl, so I cannot debug it. I'm using centos7 with CWP

**Comment by mxschmitt** [comment]
Thanks for reporting the issue @RealRunSpace. It's fixed now 👍

**Comment by RealRunSpace** [comment]
So I only execute the pull coamd, restart docker and should be fixed right?

**Comment by mxschmitt** [comment]
Unfortunately not, you have to adjust your `config.ini` and set:
`YoutubeDLPath = "/usr/local/bin/youtube-dl"`

**Comment by RealRunSpace** [comment]
Sorry to ask, but how can I edit this config? With exec I can enter in the container, but I can't use nano or another edito, so how can I do it?

**Comment by irgendwr** [comment]
If you're using volumes like shown in the readme then you can use `nano /opt/sinusbot/data/config.ini` on your docker-host.

**Comment by RealRunSpace** [comment]
ok thanks!
