### ISSUE TITLE
can start my server anymore

### ISSUE THREAD

**Issue by kenosama** [SinusBot/docker#29]
i've a docker version installed on my qnap ts453, it worked okay until few day ago 
i got this message i try to re-install the whole app and does the same :/
this i what i get into the console

youtube-dl is up-to-date (2019.04.01)                                                                                                       
youtube-dl updated                                                                                                                          
Starting SinusBot...                                                                                                                        
This version has expired. Please download a newer version from the official SinusBot website and upgrade.

**Comment by irgendwr** [comment]
pull/update to the latest image

**Comment by kenosama** [comment]
even i i try to install from sratch it wont take the last version? and how do i pull the update?

**Comment by irgendwr** [comment]
> even i i try to install from sratch it wont take the last version? 

Just tested a new installation and it works fine. It installs the current version `1.0.0-alpha.6-5ddc294` as it should.

> how do i pull the update?

https://github.com/SinusBot/docker#updating-the-image

Are you sure that you used our docker repository and not an unofficial one?
If yes, then: How did you install it?

**Comment by kenosama** [comment]
okay i had to suppress all the app container station to be able to make a clean install and it's working like a charm... i just wonder how i work to update it on this app (Qnap container station) 

Thanks for the help :)
