### ISSUE TITLE
Problems running as non root

### ISSUE THREAD

**Issue by dampfklon** [SinusBot/docker#32]
When i try to run the container as a non-root user like stated in the README i ran into the problem that the entry script can't create the symlink for the config (permission denied) and sinusbot cant start.

**Comment by irgendwr** [comment]
Sorry, my fault - it's fixed now. #27

1. [Update](https://github.com/SinusBot/docker#updating)
2. Follow the updated [section in the readme](https://github.com/SinusBot/docker#unprivileged-user)
