### ISSUE TITLE
Ldap auth support?

### ISSUE THREAD

**Issue by Spacelord09** [SinusBot/docker#37]
Hey guys!
Firstly I must thank you for this realy nice music bot with a realy nice web gui!
So let's get back to my question: Is Ldap support planed? or/and can it be implementet in near future?

I have a global ldap server for my staff to login to our systems.
This makes the administration effort extremely easy for me and my admins.

**Comment by irgendwr** [comment]
Hi, please use the [forum](https://forum.sinusbot.com/forums/bugs-feature-requests.4/) for suggestions and bug reports related to the sinusbot.
