### ISSUE TITLE
@startup setpriv: libcap-ng is too old for "all" caps

### ISSUE THREAD

**Issue by stertzi2012** [SinusBot/docker#39]
Hello everyone,
The docker container Sinusbot/docker:lastes does not start. It is only shown in the log "setpriv: libcap-ng is too old for "all" caps".

Extract from the log:

Updating youtube-dl...
youtube-dl is up-to-date (2020.09.20)
User ID: 0
Change file owner...
Drop privileges...
Starting SinusBot...
PID: 11
setpriv: libcap-ng is too old for "all" caps

To my system:
Opensuse Thumbleweed (up to date)
What can I do to get it running again?

**Comment by mxschmitt** [comment]
Seems like its an upstream bug, which kernel are you using? https://bugs.archlinux.org/task/67781

**Comment by stertzi2012** [comment]
Hi,
My Release is Linux opensuse 5.8.10-1-default #1 SMP Mon Sep 21 11:00:19 UTC 2020 (af3e800) x86_64 x86_64 x86_64 GNU/Linux

**Comment by mxschmitt** [comment]
Seems like not a bug or issue which we can fix on our side. It seems to be persistent on kernel version 5.8.X as linked in the issue above.

**Comment by MacGyver27** [comment]
Same here. Not able to start the container.. @stertzi2012 were you able to find a workaround? Thx, Michal

**Comment by MacGyver27** [comment]
@mxschmitt what do you propose? they closed the bug with new releasing new versions:
```
Closed by  Christian Hesse (eworm)
Wednesday, 02 September 2020, 09:10 GMT
Reason for closing:  Fixed
Additional comments about closing:  libcap-ng 0.7.11-2
util-linux 2.36-3
```

**Comment by irgendwr** [comment]
This should be fixed now, it would be nice if someone could test it and provide feedback.

Make sure to update as described in the [README](https://github.com/SinusBot/docker#updating).

**Comment by stertzi2012** [comment]
I can confirm that the error is now fixed.
