### ISSUE TITLE
Latest build having issues with dl & playback of youtube content

### ISSUE THREAD

**Issue by casualcodr** [SinusBot/docker#43]
Hi,

after upgrading to the latest build !yt and !qyt do not work any more.
Stored youtube playlists won't play either.
Maybe you could have a look.

Thanks,Stay Safe !

**Comment by grimsi** [comment]
I'm having the same problem since a week. Youtube DL is installed in the container (so no issues there) and the commands get recognized (bot sends "✅ done!"). But no sound and the current title does not show up in the web interface.

**Comment by mxschmitt** [comment]
Its a known problem, see [here](https://forum.sinusbot.com/threads/sinusbot-doesnt-properly-call-youtube-dl-wrong-flags-passed.8290/#post-48190), needs to be fixed in the SinusBot.

**Comment by casualcodr** [comment]
Thanks @mxschmitt for clarification. 
Any hint for an estimated fix ? No pressure though !

**Comment by randomic** [comment]
It should be fixed in `sinusbot-1.0.0-beta.14-dc94a7c` according to https://forum.sinusbot.com/threads/could-not-decode-downloader-output-json-cannot-unmarshal-number-127-37-into-go-struct-field-ytdlformat-abr-of-type-int.8291/post-48509

**Comment by poqdavid** [comment]
I am also looking forward to this fix :) been having this problem for a while now not being pushy but any idea when `sinusbot-1.0.0-beta.14-dc94a7c` will be available on the docker?

**Comment by mxschmitt** [comment]
Updated the version, should be fixed now.
