### ISSUE TITLE
Bot is not connecting to teamspeak3 server

### ISSUE THREAD

**Issue by EpicJosch** [SinusBot/docker#52]
Hi. I'm using the latest version of teamspeak server and the latest version of sinusbot. Both teamspeak server and sinusbot are running in docker. The sinusbot cannot connect to the teamspeak server. This is weird because a while ago I set the sinusbot up just the way I did now and it worked fine. Now the bot can't connect anymore. I did some research and found that the only possible reason is that the teamspeak client used in ur docker image is to old? Would it be possible to update your docker image to use the latest teamspeak client?

**Comment by FlorianLeChat** [comment]
This is impossible because the installer will always use the latest version available: https://github.com/SinusBot/docker/blob/a85f12991538d2e95daea1f2aab06de3d43b91bf/discord/install.sh#L66

**Comment by EpicJosch** [comment]
Sorry my bad. Used the wrong server address to which the bot should connect. Closed.
